### ISSUE TITLE
Remove module jpastreamer.analytics 

### ISSUE THREAD

**Issue by minborg** [speedment/jpa-streamer#107]
Add additional properties as package names.

**Comment by julgus** [comment]
We should also discuss if, and if so how, we may allow disabling of Google Analytics.

**Comment by julgus** [comment]
Instead of tracking more data with GA we should provide a way to easily disable this feature.

**Comment by julgus** [comment]
We've taken into account feedback from numerous users expressing concerns about the utilization of Google Analytics, which can be discouraging or even restricted in various scenarios. To address this, we've concluded that we will eliminate the module responsible for transmitting data to GA. This change will come into effect with our upcoming release.
