### ISSUE TITLE
Add terminal operation toList()

### ISSUE THREAD

**Issue by minborg** [speedment/jpa-streamer#114]

**Comment by julgus** [comment]
Java 16 and later versions have a default implementation of this method that is automatically optimizable by JPAStreamer. Thus no custom implementation is needed and a result list can be composed as follows: 

```
List<Film> = jpaStreamer.of(Film.class) 
        .filter(Film$.title.startsWith("T")) 
        .toList(); 
```

This is the new equivalent of the terminal operation .`Collector(Collections.toList())`.
