### ISSUE TITLE
Honor DO_NOT_TRACK environment variable

### ISSUE THREAD

**Issue by jreznot** [speedment/jpa-streamer#156]
Please disable Google analytics tracking if there is `DO_NOT_TRACK` environment variable.
So users will be able to opt-out with:
```
export DO_NOT_TRACK=1
```

Many other OSS products support it already:
https://consoledonottrack.com/

**Comment by minborg** [comment]
This would be easy to do from a technical point of view. 

However, the current business model relies on the sponsor either counting the actual use of the product or knowing who is running JPAstreamer.  If you want to turn off analytics, simply send a mail to `info@jpastreamer.org`.

If anyone can suggest a better business model, we are eager to hear about it.

**Comment by jreznot** [comment]
I would recommend looking at JooQ as an example of sustainable OSS product with monetization.

**Comment by minborg** [comment]
JOOQ is a good example of a successful product and business model. However, our sponsor is not in the same situation as when JOOQ was incepted. So, unfortunately, that is not a viable model in this case.
