### ISSUE TITLE
Bug in query results

### ISSUE THREAD

**Issue by doardin** [speedment/jpa-streamer#163]
I noticed a bug regarding the results of some queries, JPA Streamer does not always return what is actually in the database.  My test was simple, I did a specific query that was based on the status of a column, which returned only records whose column specified that record was active and I realized that even after modifying the column's value directly in the database, JPA still returned the record which it shouldn't return, after some tests and revisions I noticed this bug in JPA and for it to return the data correctly I needed to restart the application, I looked for some documentation that talked about it but unfortunately I didn't find anything so decide report this error through github.

**Comment by doardin** [comment]
I solved my problem using streamer.close() and streamer.open()

**Comment by minborg** [comment]
Can you provide a code snippet showing the problem please?

**Comment by doardin** [comment]
I noticed that bug it happens if you update values directly by database.

<h4>INITIAL VALUES</h4>
<img width="236" alt="Captura de Tela 2022-03-10 às 11 25 12" src="https://user-images.githubusercontent.com/65371964/157682102-91734f5b-2890-46b8-9986-04de03f619b6.png">

**Database**
<img width="182" alt="Captura de Tela 2022-03-10 às 11 08 43" src="https://user-images.githubusercontent.com/65371964/157680948-215e2dba-2d22-4c5e-adfa-9ad557e60f37.png">

I updated directly by database, the new values is
<img width="173" alt="Captura de Tela 2022-03-10 às 11 26 30" src="https://user-images.githubusercontent.com/65371964/157682324-e955dafe-eb5b-4e27-bdb3-df2d40fa4a70.png">

but the response of application is the old values of object
<img width="224" alt="Captura de Tela 2022-03-10 às 11 27 19" src="https://user-images.githubusercontent.com/65371964/157682477-ae383dcd-9870-4a87-a677-0a354ab74f63.png">


[source code](https://github.com/doardin/jpa-streamer-bug-example) i used to show this bug

**Comment by julgus** [comment]
This issue arises as the `JPAStreamer` instance reuses a single JPA `EntityManager` throughout its lifetime.  JPA's first-level cache automatically caches the query results which means repeated queries are not run against the database but the cache. This explains why the change is not reflected in the application until restart. We are working on a solution for the next release.
