### ISSUE TITLE
Provide CDI integration / Quarkus extension

### ISSUE THREAD

**Issue by tokazio** [speedment/jpa-streamer#193]
Hello, i've seen the Spring integration docs here https://speedment.github.io/jpa-streamer/jpa-streamer/1.0.1/get-jpa-streamer/spring_integration.html

I'm using weld or quarkus for my applications.

What about a CDI integration ?

**Comment by minborg** [comment]
Certainly a good proposal.

**Comment by tokazio** [comment]
I think to create a JPAStreamerProducer class in integration/cdi with this code

```
import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.inject.Produces;
import javax.persistence.EntityManagerFactory;

@ApplicationScoped
public class JPAStreamerProducer {

  @Produces
    JPAStreamer streamer(EntityManagerFactory entityManagerFactory){
        return JPAStreamer.createJPAStreamerBuilder(entityManagerFactory).build();
    }

}
```

I'm actually using this in a quarkus application and it's working.

The quarkus plugin should be interesting for the 'native' part and for the reflection configuration
