### ISSUE TITLE
Count doesn't returning the good value

### ISSUE THREAD

**Issue by tokazio** [speedment/jpa-streamer#206]
Using hibernate and JPAStreamer
When i do
`
Streamer.stream(Ett class).count()
`
It's returning 1 while
`
Select count(*) from t_ett
`
Is returning the good number of line in the table.

JPAStreamer use a count(field) instead of count(*) when quering, that's the only difference i've seen.

Is there a cache somewhere ? Why JPAStreamer isn't returning the good value ?

**Comment by minborg** [comment]
JPAStreamer never caches values internally. If you run the https://github.com/speedment/jpa-streamer-demo/tree/master/hibernate demo on your settings, do you get the same problem?
