### ISSUE TITLE
Hibernate Core support (org.hibernate.orm:hibernate-core:6.0.1.Final)

### ISSUE THREAD

**Issue by doriangrelu** [speedment/jpa-streamer#256]
Support the last version of Hibernate that Provide Jakarta EntityManagerFactory. 
Artifact -->org.hibernate.orm:hibernate-core:6.0.1.Final

**Comment by davidivkovic** [comment]
Any updates?

**Comment by julgus** [comment]
This was fixed in the latest release 3.0.0! Forgot to close this issue.
