### ISSUE TITLE
JPA Streamer Field Generator Processor syntax errors in generated sources

### ISSUE THREAD

**Issue by imdad-sarwar** [speedment/jpa-streamer#271]
As attached, I tried to compile my gradle project on MAC many times but failed because of syntax errors in your plugin generated sources. All source levels, 17, 16, 11, 8 were tried but compilation failed. Respective scrrenshots attached
<img width="830" alt="User$ java" src="https://user-images.githubusercontent.com/22787561/187376706-f4440d4c-b978-4a2d-9b43-39366ff45c83.png">

<img width="1440" alt="field_gen_err_java8" src="https://user-images.githubusercontent.com/22787561/187376249-692462dc-c5d3-4bd7-9dde-5f3871269cfa.png">
<img width="1430" alt="field_gen_err_java17" src="https://user-images.githubusercontent.com/22787561/187376308-7b1ea66f-1d5f-4002-9b22-620ab6bad7bd.png">
<img width="1427" alt="filed_gen_err_java11" src="https://user-images.githubusercontent.com/22787561/187376318-15b87f49-4ae9-468f-801f-a9444d282af7.png">

**Comment by minborg** [comment]
Hi and thanks for reporting this issue. Are you able to post the original entity class `User` so we could reproduce the problem?

**Comment by imdad-sarwar** [comment]
Hello, below is the User class code. And also clarify, if code gen works for for Embeddable JPA entities ?

package com.directdebit.persistance.entities;

import javax.persistence.*;
import javax.validation.constraints.NotEmpty;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
@Entity
@Table(name="user")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User  implements Serializable{
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_shared")
    @SequenceGenerator(name = "seq_shared", sequenceName = "seq_shared",allocationSize = 1)
    Long id;

    @NotEmpty
    private String username;

    @NotEmpty
    private String password;

    private boolean enabled;

    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "role_id")
    private Role role;


    
}

**Comment by imdad-sarwar** [comment]
Hi, how can I apply this fix to my code. Shall I remove lombok extensions in order to use JPA streamer library. Still I have same issue and no .class files generating on classpath

**Comment by julgus** [comment]
We will issue a new release in our near future pipeline. Pulling the source and building your own snapshot remains an option until then. The Lombok extension pairs well with JPA Streamer and should not cause any trouble.

**Comment by laszlo-amptech** [comment]
Hi.  I am experiencing the same issue.  Do you have an ETA on the new release with this fix?

**Comment by julgus** [comment]
@laszlo-amptech Try the new release. If you are still running into problems, please open a new issue and describe your context in greater detail. Thanks.
