### ISSUE TITLE
Spring sts 4.11 can not import, generated class

### ISSUE THREAD

**Issue by elvinotan** [speedment/jpa-streamer#275]
The program is running well, but spring sts editor, complain about jpastreamer generated class

<img width="349" alt="image" src="https://user-images.githubusercontent.com/19750679/192228999-7139df39-a59e-42a2-8326-7507c5853624.png">

**Comment by elvinotan** [comment]
Solved, you need to reordering, and put target/generated-sources/anntations on top of src/main/java
![image](https://user-images.githubusercontent.com/19750679/192425432-8e9a26ca-84f9-4568-8535-f9e1566c548b.png)

**Comment by julgus** [comment]
Thanks for sharing the solution!
