### ISSUE TITLE
Optimize terminating operations

### ISSUE THREAD

**Issue by dekmm** [speedment/jpa-streamer#31]
Some terminal operations can be expressed as a combination of multiple intermediate operations, making them easier to represent in SQL:

- [x] `AnyMatch`
`.anyMatch(p)` can be expressed as `.filter(p).limit(1).count() > 0)`
- [x] `NoneMatch`
`.noneMatch(p)` can be expressed as `.filter(p).limit(1).count() = 0`

Some terminal operations can be enhanced with certain intermediate operations in order to optimize the SQL query that is being executed:

- [x] `FindFirst`
`.findFirst()` can be expressed as `.limit(1).findFirst()` to restrict the size of the `ResultSet`
- [x] `FindAny` can be expressed as `.unordered().limit(1).findAny()`

**Comment by julgus** [comment]
Work appended to the 'terminal' branch.
