### ISSUE TITLE
Implements @QueryHints or similar

### ISSUE THREAD

**Issue by nitroin** [speedment/jpa-streamer#320]
To process large amount of data is sometime needed to provide additional configuration for the underlying JDBC driver, eg. to disable full resultsets cache in ram.

This is particularly useful to enable cursor "streaming" on the dbms side: eg. [getting-results-based-on-a-cursor](https://jdbc.postgresql.org/documentation/query/#getting-results-based-on-a-cursor).

Usually this is implemented with `@QueryHints` annotations in spring or `.withHint` methods on Panache repositories.

```java
    return findAll()
        .withHint(QueryHints.HINT_FETCH_SIZE, 50)
        .withHint(QueryHints.HINT_READONLY, true)
        .stream()
        .map(this::detach);
```

I strongly think that this feature greatly fits JPAStreamer as it permits streaming at all layers involved.

**Comment by julgus** [comment]
Thank you for the suggestion! I will take a closer look.

**Comment by nitroin** [comment]
I think I can try drafting a PR if you find it valuable. I was thinking of expanding `StreamConfig` capabilities...

**Comment by julgus** [comment]
Yes, that would definitely be valuable. Expanding the `StreamConfiguration` sounds like a good way to go!

**Comment by julgus** [comment]
Sorry for not paying attention to your draft sooner! Completely missed it. I've left a comment regarding missing JavaDocs, other than that it looks great. Thank you for helping out!

Before I can merge your changes I need you to sign a Contributor Licence Agreement. We have described why and how that is done here: [https://github.com/speedment/jpa-streamer/blob/master/CONTRIBUTING.md](https://github.com/speedment/jpa-streamer/blob/master/CONTRIBUTING.md).

**Comment by julgus** [comment]
I just merged your changes into the development branch. I cannot say for sure when we will make the next official release but most likely within the next month. Your name is now also on the list of contributors. 

Thanks again for your valuable input and contribution!

**Comment by julgus** [comment]
Almost forgot! We need to document this feature in our [docs](https://speedment.github.io/jpa-streamer) to make sure anyone who searches for "query hints" can find it. I made an attempt to write something up. Do you mind checking my [commit](https://github.com/speedment/jpa-streamer/commit/d1b647359a614a4756a51004523968cf4fb79545) to see if it needs any changes or additions in your opinion?

**Comment by nitroin** [comment]
LGTM!
