### ISSUE TITLE
General pipeline optimizations

### ISSUE THREAD

**Issue by dekmm** [speedment/jpa-streamer#33]
If at least one of the following conditions are true:
- the stream is unordered (e.g. the Stream::unordered has been called) 
- the terminal operation does not require the order to be preserved (for example forEach and min)
- the stream is parallel and terminal operation does not require the order to be preserved for parallel streams

Then, the longest consecutive string of intermediate operations starting from the back that only affects the order of elements (i.e. Sorted) can be removed.

**Comment by julgus** [comment]
Closing this issue as it seems like this was already implemented in `RemoveOrderAffectingOperations`.
