### ISSUE TITLE
Anonymous Lambda reordering

### ISSUE THREAD

**Issue by dekmm** [speedment/jpa-streamer#35]
Anonymous Lambdas should be moved down the order as much as possible to allow as much as possible of the stream to be executed on the database side.

**Comment by julgus** [comment]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-a8a103db-7fff-633e-475c-51da1d0892ca"><div dir="ltr" style="margin-left:0pt;" align="left">

Original Operation | Operations that can be moved before/after the original operation
-- | --
filter | sorted, distinct
sorted | filter, distinct
distinct | filter, sorted

</div></b>
