### ISSUE TITLE
Cannot generate $ icon files under annotations folder of generated-sources

### ISSUE THREAD

**Issue by Rapter1990** [speedment/jpa-streamer#359]
I tried to implement an example of Spring Boot with the usage of `jpaStreamer`. I use `Intellij Idea` to handle with it. I have a problem in `jpaStreamer.stream`.

Here are the dependencies shown below

    <jpastream.version>1.1.4</jpastream.version>
    
    <dependency>
    	<groupId>com.speedment.jpastreamer</groupId>
    	<artifactId>jpastreamer-core</artifactId>
    	<version>${jpastream.version}</version>
    </dependency>
    
    <dependency>
    	<groupId>com.speedment.jpastreamer.integration.spring</groupId>
    	<artifactId>spring-boot-jpastreamer-autoconfigure</artifactId>
    	<version>${jpastream.version}</version>
    </dependency>

Here is the sample method of UserService shown below

    public List<User> findAllForJpaStreamer() {
       return jpaStreamer.stream(User.class).
              sorted(User$.id).
              collect(Collectors.toList());
    }

I get this error message shown below

    Cannot resolve symbol 'User$'

Here is the screenshot shown below

[![enter image description here][1]][1]

[![enter image description here][2]][2]

How can I fix it?

Here is the repo : [Link][3]

  [1]: https://i.stack.imgur.com/LTYWL.png
  [2]: https://i.stack.imgur.com/mlxXI.png
  [3]: https://github.com/Rapter1990/jpastreamer

**Comment by julgus** [comment]
I cannot see that you have a `User` Entity, I only find a `Person` Entity. JPAStreamer only generates entities from the existing JPA model that you have. 

I also note that the `Person` class is using `jakarta.persistence` which is part of JPA 3. JPAStreamer version 1.1.4 is only compatible with JPA 2, but if you update `jpastreamer.version` to 3.0.3 and rebuild your project you should get a `Person$` generated in target/generated-sources. Give it a try and let me know how it goes.

**Comment by julgus** [comment]
Also thanks for providing a complete example application - helps a lot!

**Comment by Rapter1990** [comment]
@julgus I solved the issue and I forgot to inform you about that. I implemented a config class to handle with that.
Thank you for your answer.

**Comment by julgus** [comment]
Great, thanks for the update!
