### ISSUE TITLE
Metamodel classes not generated properly when using hibernate validator with quarkus

### ISSUE THREAD

**Issue by iwe-7** [speedment/jpa-streamer#368]
**Describe the bug**
Metamodel classes are not generated properly when using [hibernate validator](https://quarkus.io/guides/validation) with quarkus.

**Expected behavior**
Correct generation of `$.java` metamodel classes

**Actual behavior**
It seems that the paths of `@jakarta.validation.constraints Annotations` get mixed into the imports of other classes during metamodel generation:
![image](https://github.com/speedment/jpa-streamer/assets/43415575/ca606d3d-9858-40cc-a83d-1b30d83c257b)

**How To Reproduce**
- quarkus project with hibernate panache orm,  [hibernate validator](https://quarkus.io/guides/validation) and jpa streamer
- create a entity and annotate one of its fields with a `jakarta.validation.constraints` annotation e.g.:
 ```java
    @NotBlank
    private String name;
````
- try to regenerate jpastreamer metamodel (mvn clean install) -> error should arise in generated classes

**Build tool**
Maven 3.9.2

**JPAStreamer version**
JPAStreamer 3.0.2Final

**JPA Provider**
Quarkus Hibernate Panache 3.2.0.Final 

**Java Version**
Java 17.0.6

**Comment by julgus** [comment]
Thank you for reporting this, I will have a look ASAP!

**Comment by julgus** [comment]
I've identified the issue, which should be fixed in the release planned for this week. Thanks again for reporting, it was really helpful.
