### ISSUE TITLE
jdk 17 support

### ISSUE THREAD

**Issue by fernando88to** [speedment/jpa-streamer#378]
I'm using jpa-stream together with quarkus and when running the project it throws the following exception 

`
Note: JPA Streamer Field Generator Processor
warning: Supported source version 'RELEASE_11' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '17'
Note: [JPAStreamer Field Generator Processor] Generating class for: com.fernando.entities.User
1 warning
`

Does the jpa-stream project support jdk 17?

**Comment by julgus** [comment]
JPAStreamer supports Java 17! This PR might help clarify why the warning exists: https://github.com/speedment/jpa-streamer/pull/327.
